/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_internet_subscription.views;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import pj_internet_subscription.C_internet_subscription;
import pj_internet_subscription.model.M_Authorization;
import pj_internet_subscription.model.M_User;

/**
 *
 * @author adjedjm
 */
public class V_Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Main.class.getName());

    /**
     * Creates new form V_Main
     */
    private Map<String, Object> menuMap = new HashMap<>();
    private C_internet_subscription controller;
    private boolean firstVisit = true;
    private LinkedHashMap <Integer, M_Authorization> authList;
    private M_Authorization authComponent;
    private Object menuContent;
    private String classe, errorMessage = null;
    private JMenu mn;
    private JMenuItem mi;
    private M_User userSession;
    
     private void scanMenus(JMenuBar menuBar){
        for (int i = 0; i < menuBar .getMenuCount() ; i++){
            JMenu mn = menuBar.getMenu(i);
            menuMap.put(mn.getName(), mn);
            mn.setVisible(false);
            // Ajoute les menus à la map
            // Scanner les éléments (items) de chaque menu
            for (int j = 0; j < mn.getItemCount(); j++) {
               JMenuItem mi = mn.getItem(j);
                menuMap.put(mi.getName(), mi);
                mi.setVisible(false);          
            }
        }
        mn_file.setVisible(true);
        mi_exit.setVisible(true);
        
    }
    
     public void isConnected(boolean valeur){
        if(firstVisit == true){
            scanMenus(mb_menu);
            firstVisit = false;
        }
        if (valeur == false){            
            this.lb_connection.setVisible(true);
            this.lb_email.setVisible(true);
            this.lb_password.setVisible(true);
            this.tf_email.setVisible(true);
            this.tf_password.setVisible(true);
            this.bt_connect.setVisible(true);
            lb_session.setVisible(false);
        }
        else {
            for (Integer uneCle : authList.keySet()) {
                authComponent = authList.get(uneCle);
                
                menuContent = menuMap.get(authComponent.getCode());
                
                classe = menuContent.getClass().toString();
                switch (classe){
                    case "class javax.swing.JMenu" -> {  mn = (JMenu) menuContent;
                        mn.setVisible(true);
                    }
                    case "class javax.swing.JMenuItem" -> {   mi = (JMenuItem) menuContent;
                       mi.setVisible(true);
                    }
                      
                    }
                }
                
            
            this.lb_connection.setVisible(false);
            this.lb_email.setVisible(false);
            this.lb_password.setVisible(false);
            this.tf_email.setVisible(false);
            this.tf_password.setVisible(false);
            this.bt_connect.setVisible(false);
            lb_session.setVisible(true);
        }
    }
     
    public void display(M_User userSession, LinkedHashMap <Integer, M_Authorization> authList, String errorMessage){
        this.authList = authList;
        this.errorMessage = errorMessage;
        this.userSession = userSession;
        if (userSession == null){
            isConnected(false);
        }
        else {
            lb_session.setText("Welcome "+userSession.getFirst_name()+" "+userSession.getLast_name());
            isConnected(true);
        }
        this.setVisible(true);
    }
    
    public V_Main(C_internet_subscription controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_error = new javax.swing.JOptionPane();
        tf_email = new javax.swing.JTextField();
        lb_connection = new javax.swing.JLabel();
        tf_password = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        bt_connect = new javax.swing.JButton();
        lb_session = new javax.swing.JLabel();
        mb_menu = new javax.swing.JMenuBar();
        mn_file = new javax.swing.JMenu();
        mi_disconnect = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();
        mn_parameters = new javax.swing.JMenu();
        mi_rooms = new javax.swing.JMenuItem();
        mi_users = new javax.swing.JMenuItem();
        mi_computer = new javax.swing.JMenuItem();
        mi_paymentMeth = new javax.swing.JMenuItem();
        mn_management = new javax.swing.JMenu();
        mi_subscriptions = new javax.swing.JMenuItem();
        mi_accommodations = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lb_connection.setText("Connection");

        lb_email.setText("Email : ");

        lb_password.setText("Password :");

        bt_connect.setText("Connect");
        bt_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connectActionPerformed(evt);
            }
        });

        lb_session.setText("a");
        lb_session.setToolTipText("");

        mb_menu.setName("mb_menu"); // NOI18N

        mn_file.setText("File");
        mn_file.setName("mn_file"); // NOI18N

        mi_disconnect.setText("Disconnect");
        mi_disconnect.setToolTipText("");
        mi_disconnect.setName("mi_disconnect"); // NOI18N
        mn_file.add(mi_disconnect);

        mi_exit.setText("Exit");
        mi_exit.setName("mi_exit"); // NOI18N
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        mn_file.add(mi_exit);

        mb_menu.add(mn_file);

        mn_parameters.setText("Parameters");
        mn_parameters.setName("mn_parameters"); // NOI18N

        mi_rooms.setText("Rooms");
        mi_rooms.setName("mi_rooms"); // NOI18N
        mn_parameters.add(mi_rooms);

        mi_users.setText("Users");
        mi_users.setName("mi_users"); // NOI18N
        mn_parameters.add(mi_users);

        mi_computer.setText("Computer Sys/AV");
        mi_computer.setName("mi_computer"); // NOI18N
        mn_parameters.add(mi_computer);

        mi_paymentMeth.setText("Payment Methods");
        mi_paymentMeth.setName("mi_paymentMeth"); // NOI18N
        mn_parameters.add(mi_paymentMeth);

        mb_menu.add(mn_parameters);

        mn_management.setText("Management");
        mn_management.setName("mn_management"); // NOI18N

        mi_subscriptions.setText("Subscriptions");
        mi_subscriptions.setName("mi_subscriptions"); // NOI18N
        mi_subscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_subscriptionsActionPerformed(evt);
            }
        });
        mn_management.add(mi_subscriptions);

        mi_accommodations.setText("Accommodations");
        mi_accommodations.setName("mi_accommodations"); // NOI18N
        mn_management.add(mi_accommodations);

        mb_menu.add(mn_management);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_password)
                                .addGap(18, 18, 18)
                                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_email)
                                .addGap(18, 18, 18)
                                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lb_connection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_connect)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_session, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lb_connection)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_password)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(bt_connect)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
        this.formWindowClosing(null);
        System.exit(0);
    }//GEN-LAST:event_mi_exitActionPerformed

    private void mi_subscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_subscriptionsActionPerformed
        try {
            controller.subscriptionPage(0);
        } catch (SQLException ex) {
            System.getLogger(V_Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_subscriptionsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         try {
            controller.disconnect();
        } catch (SQLException ex) {
            System.getLogger(V_Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void bt_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connectActionPerformed
         try {
            controller.connectToSession(tf_email.getText(), tf_password.getText());
            if (userSession == null && errorMessage == null){
                op_error.showConfirmDialog(this, "Mauvaises informations");
            }
            else if (userSession == null && errorMessage != null) {
                op_error.showConfirmDialog(this, errorMessage);
            }
        } catch (SQLException ex) {  
            
            System.getLogger(V_Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bt_connectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_Main(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connect;
    private javax.swing.JLabel lb_connection;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_session;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_accommodations;
    private javax.swing.JMenuItem mi_computer;
    private javax.swing.JMenuItem mi_disconnect;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JMenuItem mi_paymentMeth;
    private javax.swing.JMenuItem mi_rooms;
    private javax.swing.JMenuItem mi_subscriptions;
    private javax.swing.JMenuItem mi_users;
    private javax.swing.JMenu mn_file;
    private javax.swing.JMenu mn_management;
    private javax.swing.JMenu mn_parameters;
    private javax.swing.JOptionPane op_error;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_password;
    // End of variables declaration//GEN-END:variables
}
