/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_internet_subscription.views;

import java.util.LinkedHashMap;
import javax.swing.table.DefaultTableModel;
import pj_internet_subscription.C_internet_subscription;
import pj_internet_subscription.model.M_Room;
import pj_internet_subscription.model.M_Subscription;

/**
 *
 * @author adjedjm
 */
public class V_Room extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Room.class.getName());

    /**
     * Creates new form V_Rooms
     */
    
    private C_internet_subscription controller;
    private DefaultTableModel dm_tb_room;
    private M_Room selectedRoom;
    private LinkedHashMap <String, M_Room> roomList;
    
    private void roomTable(LinkedHashMap <String, M_Room> roomList) {
       this.roomList = roomList;
       dm_tb_room.setRowCount(0);
       for (String key : roomList.keySet()) {
           M_Room room = roomList.get(key);
           dm_tb_room.addRow(new Object[]{room.getCode(), room.getCapacity()});
           
       }
    }

    public void display(LinkedHashMap <String, M_Room> roomList){
        dm_tb_room = (DefaultTableModel) tb_rooms.getModel();
        roomTable(roomList);
        this.setVisible(true);
    }
    
    public V_Room(C_internet_subscription controller,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controller = controller;

    }
    
    public void roomInfo(){
        if (tb_rooms.getSelectedRow()!=-1){
             selectedRoom = roomList.get(dm_tb_room.getValueAt(tb_rooms.getSelectedRow(), 0));
        }
    }
    
    public void errorSelection(String errorMessage){
        if (tb_rooms.getSelectedRow() == -1){
            op_error.showMessageDialog(this, errorMessage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_error = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_rooms = new javax.swing.JTable();
        bt_details = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_modify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        bt_next = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb_rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_rooms);
        if (tb_rooms.getColumnModel().getColumnCount() > 0) {
            tb_rooms.getColumnModel().getColumn(0).setResizable(false);
            tb_rooms.getColumnModel().getColumn(1).setResizable(false);
        }

        bt_details.setText("Details");
        bt_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_detailsActionPerformed(evt);
            }
        });

        bt_add.setText("Add");

        bt_modify.setText("Modify");

        jLabel1.setText("Room Management");

        bt_back.setText("Back");

        bt_next.setText("Next");

        bt_delete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(bt_back)
                        .addGap(164, 164, 164)
                        .addComponent(bt_next)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(bt_details)
                        .addGap(85, 85, 85)
                        .addComponent(bt_add)
                        .addGap(87, 87, 87)
                        .addComponent(bt_modify)
                        .addGap(81, 81, 81)
                        .addComponent(bt_delete)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_back)
                    .addComponent(bt_next))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_detailsActionPerformed
        roomInfo();
        errorSelection("Please select a room");
        controller.roomCrud("detail", selectedRoom);
    }//GEN-LAST:event_bt_detailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                V_Room dialog = new V_Room(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_details;
    private javax.swing.JButton bt_modify;
    private javax.swing.JButton bt_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane op_error;
    private javax.swing.JTable tb_rooms;
    // End of variables declaration//GEN-END:variables
}
