/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_internet_subscription.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jdk.jshell.JShell;
import pj_internet_subscription.C_internet_subscription;
import pj_internet_subscription.model.M_Computer;
import pj_internet_subscription.model.M_Method;
import pj_internet_subscription.model.M_Payment;
import pj_internet_subscription.model.M_Product;
import pj_internet_subscription.model.M_Subscription;

/**
 *
 * @author adjedjm
 */
public class V_SubscriptionAdditions extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_SubscriptionAdditions.class.getName());
    private C_internet_subscription controller;
    private String action;
    private DefaultTableModel dm_tb_products;
    private int nbRow;
    private ArrayList<M_Product> productArray;
    private LinkedHashMap<Integer, M_Product> addedProductList, allProducts, deletedProductList;
    private M_Subscription currentSubscription;
    
    private void displayContent(String action) throws SQLException{
        this.action = action;
        switch (action) {
            case "products" : 
                pn_products.setVisible(true);
                pn_payments.setVisible(false);
                pn_computers.setVisible(false);
                break;
            case "computers" : 
                pn_products.setVisible(false);
                pn_payments.setVisible(false);
                pn_computers.setVisible(true);
                break; 
            case "payments" : 
                pn_products.setVisible(false);
                pn_payments.setVisible(true);
                pn_computers.setVisible(false);
                break;
            default : 
                this.controller.subscriptionCrud("modify", currentSubscription);
                this.setVisible(false);
        } 
    }
    
    
    private void productTable(LinkedHashMap<Integer, M_Product> currentProducts){
        M_Product product = null;
        nbRow = 0;
        
        dm_tb_products.setRowCount(0);        
        for (int key : currentProducts.keySet() ) {
            product = currentProducts.get(key);
            dm_tb_products.addRow(new Object[]{product.getId(), product.getDesignation(), product.getPrice(), product.getQuantity()});
            nbRow++;
            productArray.add(product);
            
        }
    }
 
    // Payment Display
    public void displayPayments(String action, M_Subscription subscription, LinkedHashMap<Integer, M_Method> paymentMethodList, LinkedHashMap<Integer, M_Payment> currentPaymentsList) throws SQLException {
        this.currentSubscription = subscription;
        displayContent(action);
        this.setVisible(true);
    }
    
    public void displayProducts(String action, M_Subscription subscription, LinkedHashMap<Integer, M_Product> productList, LinkedHashMap<Integer, M_Product> currentProductList) throws SQLException {
        addedProductList = null;
        deletedProductList = null;
        productArray = null;
        addedProductList = new LinkedHashMap();
        deletedProductList = new LinkedHashMap();    
        productArray = new ArrayList();
        this.currentSubscription = subscription;
        this.allProducts = productList;
        dm_tb_products = (DefaultTableModel) tb_products.getModel();
        displayContent(action);
        productTable(currentProductList);
        for (int id : productList.keySet()){
            cb_productList.addItem(productList.get(id).getDesignation());
        }
        this.setVisible(true);
    }
    
    public void displayComputers(String action, M_Subscription subscription, LinkedHashMap<Integer, M_Computer> currentComputers) throws SQLException {
        this.currentSubscription = subscription;        
        displayContent(action);
        this.setVisible(true);
    }
    
    /**
     * Creates new form V_SubscriptionAdditions
     */
    public V_SubscriptionAdditions(C_internet_subscription controller, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
    }
    
    public void errorSelection(JTable tb, String errorMessage){
        if (tb.getSelectedRow() == -1){
            op_error.showMessageDialog(this, errorMessage);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_error = new javax.swing.JOptionPane();
        pn_products = new javax.swing.JPanel();
        lb_productsTitle = new javax.swing.JLabel();
        bt_exitProducts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_products = new javax.swing.JTable();
        bt_deleteProduct = new javax.swing.JButton();
        cb_productList = new javax.swing.JComboBox<>();
        bt_addProduct = new javax.swing.JButton();
        pn_payments = new javax.swing.JPanel();
        pn_computers = new javax.swing.JPanel();
        mb_menu = new javax.swing.JMenuBar();
        mn_file = new javax.swing.JMenu();
        mi_close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_productsTitle.setText("Product Management");
        lb_productsTitle.setToolTipText("");

        bt_exitProducts.setText("Exit");
        bt_exitProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitProductsActionPerformed(evt);
            }
        });

        tb_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_products);
        if (tb_products.getColumnModel().getColumnCount() > 0) {
            tb_products.getColumnModel().getColumn(0).setResizable(false);
            tb_products.getColumnModel().getColumn(1).setResizable(false);
            tb_products.getColumnModel().getColumn(2).setResizable(false);
            tb_products.getColumnModel().getColumn(3).setResizable(false);
        }

        bt_deleteProduct.setText("Delete");
        bt_deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteProductActionPerformed(evt);
            }
        });

        bt_addProduct.setText("Add");
        bt_addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_productsLayout = new javax.swing.GroupLayout(pn_products);
        pn_products.setLayout(pn_productsLayout);
        pn_productsLayout.setHorizontalGroup(
            pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_productsLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_productsLayout.createSequentialGroup()
                        .addComponent(lb_productsTitle)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_addProduct)
                        .addGroup(pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_productsLayout.createSequentialGroup()
                                .addComponent(cb_productList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_deleteProduct)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_productsLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))))
            .addGroup(pn_productsLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(bt_exitProducts)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_productsLayout.setVerticalGroup(
            pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_productsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_productsTitle)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_deleteProduct)
                    .addComponent(cb_productList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_addProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(bt_exitProducts)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout pn_paymentsLayout = new javax.swing.GroupLayout(pn_payments);
        pn_payments.setLayout(pn_paymentsLayout);
        pn_paymentsLayout.setHorizontalGroup(
            pn_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pn_paymentsLayout.setVerticalGroup(
            pn_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_computersLayout = new javax.swing.GroupLayout(pn_computers);
        pn_computers.setLayout(pn_computersLayout);
        pn_computersLayout.setHorizontalGroup(
            pn_computersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pn_computersLayout.setVerticalGroup(
            pn_computersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mb_menu.setName("mb_menu"); // NOI18N

        mn_file.setText("File");
        mn_file.setName("mn_file"); // NOI18N

        mi_close.setText("Close");
        mi_close.setName("mi_close"); // NOI18N
        mi_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_closeActionPerformed(evt);
            }
        });
        mn_file.add(mi_close);

        mb_menu.add(mn_file);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pn_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_payments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_computers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_computers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(pn_payments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mi_closeActionPerformed

    private void bt_deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteProductActionPerformed
        errorSelection(tb_products, "Please select a product.");
        int productId = (Integer) dm_tb_products.getValueAt(tb_products.getSelectedRow(), 0);
        try {
            controller.deleteProductFromSub(productId, currentSubscription);
            //deletedProductList.put(productId, allProducts.get(productId));
            //dm_tb_products.removeRow(tb_products.getSelectedRow());
        } catch (SQLException ex) {
            System.getLogger(V_SubscriptionAdditions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bt_deleteProductActionPerformed

    private void bt_addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addProductActionPerformed
        M_Product selectedProduct = productArray.get(cb_productList.getSelectedIndex());
        dm_tb_products.addRow(new Object[]{selectedProduct.getId(), selectedProduct.getDesignation(), selectedProduct.getPrice()});
        addedProductList.put(selectedProduct.getId(), selectedProduct);
    }//GEN-LAST:event_bt_addProductActionPerformed

    private void bt_exitProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitProductsActionPerformed
        try {
            controller.subscriptionCrud("modify", currentSubscription);
        } catch (SQLException ex) {
            System.getLogger(V_SubscriptionAdditions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_bt_exitProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                V_SubscriptionAdditions dialog = new V_SubscriptionAdditions(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addProduct;
    private javax.swing.JButton bt_deleteProduct;
    private javax.swing.JButton bt_exitProducts;
    private javax.swing.JComboBox<String> cb_productList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_productsTitle;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_close;
    private javax.swing.JMenu mn_file;
    private javax.swing.JOptionPane op_error;
    private javax.swing.JPanel pn_computers;
    private javax.swing.JPanel pn_payments;
    private javax.swing.JPanel pn_products;
    private javax.swing.JTable tb_products;
    // End of variables declaration//GEN-END:variables
}
