/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_internet_subscription.views;

import java.sql.SQLException;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import javax.swing.table.DefaultTableModel;
import pj_internet_subscription.C_internet_subscription;
import pj_internet_subscription.model.M_Subscription;
import pj_internet_subscription.model.M_User;

/**
 *
 * @author adjedjm
 */
public class V_Subscription extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Subscription.class.getName());
    private C_internet_subscription controller;
    private DefaultTableModel dm_tb_internetSub;
    private LinkedHashMap <Integer, M_Subscription> subscriptionList; // Contains internet subscriptions.
    private int maxPageSize = 50, currentPage = 0, currentId;
    private M_Subscription selectedSubscription;
    /**
     * Creates new form V_Subscription
     */
    
    private void subscriptionTable(){
        M_Subscription subscription = null;
        dm_tb_internetSub.setRowCount(0);        
        for (int key : subscriptionList.keySet() ) {
            subscription = subscriptionList.get(key);
            dm_tb_internetSub.addRow(new Object[]{subscription.getId(), subscription.getDate_begin(), subscription.getDate_end(), subscription.getFirstName()+" "+subscription.getLastName()});
        }
    }
    
    public void display(LinkedHashMap <Integer, M_Subscription> subscriptionList){
        dm_tb_internetSub = (DefaultTableModel) tb_internetSub.getModel();
        //tb_internetSub.getColumnModel().getColumn(0).setWidth(0);
        //tb_internetSub.getColumnModel().getColumn(0).setMaxWidth(0);
        //tb_internetSub.getColumnModel().getColumn(0).setMinWidth(0);

        this.setSize(800,800);
        this.subscriptionList = subscriptionList;            
        
        if (currentPage == 0){
            bt_back.setVisible(false);
        }
        else{
            bt_back.setVisible(true);
        }
        subscriptionTable();
        this.setVisible(true);
    }
    
        public void userInformation(){
        if (tb_internetSub.getSelectedRow()!=-1){
             selectedSubscription = subscriptionList.get(dm_tb_internetSub.getValueAt(tb_internetSub.getSelectedRow(), 0));
        }
    }
    
    public V_Subscription(C_internet_subscription controller, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op_Error = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_internetSub = new javax.swing.JTable();
        bt_detailsSub = new javax.swing.JToggleButton();
        bt_next = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_modify = new javax.swing.JButton();
        mb_menu = new javax.swing.JMenuBar();
        mn_file = new javax.swing.JMenu();
        mi_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Internet subscriptions");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 122, 17);

        tb_internetSub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Subscriber", "Start Date", "End Date", "Active"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_internetSub);
        if (tb_internetSub.getColumnModel().getColumnCount() > 0) {
            tb_internetSub.getColumnModel().getColumn(0).setResizable(false);
            tb_internetSub.getColumnModel().getColumn(1).setResizable(false);
            tb_internetSub.getColumnModel().getColumn(2).setResizable(false);
            tb_internetSub.getColumnModel().getColumn(3).setResizable(false);
            tb_internetSub.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 30, 326, 336);

        bt_detailsSub.setText("Details");
        bt_detailsSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_detailsSubActionPerformed(evt);
            }
        });
        getContentPane().add(bt_detailsSub);
        bt_detailsSub.setBounds(460, 50, 90, 23);

        bt_next.setText("Next");
        bt_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nextActionPerformed(evt);
            }
        });
        getContentPane().add(bt_next);
        bt_next.setBounds(150, 380, 72, 23);

        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        getContentPane().add(bt_back);
        bt_back.setBounds(300, 380, 72, 23);

        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        getContentPane().add(bt_add);
        bt_add.setBounds(460, 110, 90, 23);

        bt_delete.setText("Delete");
        getContentPane().add(bt_delete);
        bt_delete.setBounds(460, 170, 90, 23);

        bt_modify.setText("Modify");
        getContentPane().add(bt_modify);
        bt_modify.setBounds(460, 230, 90, 23);

        mb_menu.setName("mb_menu"); // NOI18N

        mn_file.setText("File");
        mn_file.setName("mn_file"); // NOI18N

        mi_exit.setText("Exit");
        mi_exit.setName("mi_exit"); // NOI18N
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        mn_file.add(mi_exit);

        mb_menu.add(mn_file);

        setJMenuBar(mb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mi_exitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void bt_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nextActionPerformed
        currentPage++;
        try {
            controller.subscriptionPage(currentPage*maxPageSize);
        } catch (SQLException ex) {
            System.getLogger(V_Subscription.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_bt_nextActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        currentPage--; 
            try {
                controller.subscriptionPage(currentPage*maxPageSize);
            } catch (SQLException ex) {
                System.getLogger(V_Subscription.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_detailsSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_detailsSubActionPerformed
        userInformation();
        if (tb_internetSub.getSelectedRow() == -1){
            op_Error.showMessageDialog(this, "Please select a user.");
        }
        try {
            selectedSubscription.toString();
            controller.subscriptionCrud("detail", selectedSubscription);
        } catch (SQLException ex) {
            System.getLogger(V_Subscription.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_bt_detailsSubActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                V_Subscription dialog = new V_Subscription(null, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_delete;
    private javax.swing.JToggleButton bt_detailsSub;
    private javax.swing.JButton bt_modify;
    private javax.swing.JButton bt_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JMenu mn_file;
    private javax.swing.JOptionPane op_Error;
    private javax.swing.JTable tb_internetSub;
    // End of variables declaration//GEN-END:variables
}
